pow <- read.table("household_power_consumption.txt", header=TRUE, sep=";")
pow <- subset(pow, pow$Date=="1/2/2007" | pow$Date=="2/2/2007")
pow$Global_active_power <- as.numeric(pow$Global_active_power)
datetime <- as.POSIXct(paste(pow$Date, pow$Time), format="%d/%m/%Y %H:%M:%S")
sub_reading_1 <- as.numeric(pow$Sub_metering_1)
sub_reading_2 <- as.numeric(pow$Sub_metering_2)
sub_reading_3 <- as.numeric(pow$Sub_metering_3)
png("plot3.png", height=480, width=480)
plot(datetime, sub_reading_1, ylab="Energy sub metering", xlab="", type="l")
lines(datetime, sub_reading_2, type="l", col="red")
lines(datetime, sub_reading_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col=c("black", "red", "blue"))
dev.off()