pow <- read.table("household_power_consumption.txt", header=TRUE, sep=";")
pow <- subset(pow, pow$Date=="1/2/2007" | pow$Date=="2/2/2007")
pow$Global_active_power <- as.numeric(pow$Global_active_power)
datetime <- as.POSIXct(paste(pow$Date, pow$Time), format="%d/%m/%Y %H:%M:%S")
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(datetime, pow$Global_active_power, ylab="Global Active Power (kilowatts)", xlab="" , type="l")
plot(datetime, pow$Voltag, ylab="Voltage", xlab="datetime" , type="l")
sub_reading_1 <- as.numeric(pow$Sub_metering_1)
sub_reading_2 <- as.numeric(pow$Sub_metering_2)
sub_reading_3 <- as.numeric(pow$Sub_metering_3)
plot(datetime, sub_reading_1, ylab="Energy sub metering", xlab="", type="l")
lines(datetime, sub_reading_2, type="l", col="red")
lines(datetime, sub_reading_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col=c("black", "red", "blue"), cex=0.5, bty="n")
plot(datetime, pow$Global_reactive_power, ylab="Global_reactive_Power", xlab="datetime" , type="l")
dev.off()