library(ggplot2)
library(dplyr)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
combo <- merge(NEI,SCC,by="SCC")
sub <- combo %>% filter(grepl("coal", SCC.Level.Four, ignore.case=TRUE))
sub <- sub %>% filter(grepl("comb", SCC.Level.One, ignore.case=TRUE))
##head(sub)
agg <- aggregate(sub$Emissions, by=list(sub$year), sum)
names(agg) <- c("Year", "Emissions")
##head(agg)
png("plot4(2).png")
barplot(agg$Emissions, names.arg=as.character(agg$Year),xlab="Years", ylab="PM 2.5 Emissions", main="Coal Emissions from 1999 to 2008")
dev.off()