library(ggplot2)
library(dplyr)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
combo <- merge(NEI,SCC,by="SCC")
sub <- subset(combo, combo$fips=="24510")
sub1 <- sub %>% filter(grepl("vehicle", SCC.Level.Two, ignore.case=TRUE))
agg <- aggregate(sub1$Emissions, by=list(sub1$year), sum)
names(agg) <- c("Year", "Emissions")
head(agg)
png("plot5(2).png")
barplot(agg$Emissions, names.arg=as.character(agg$Year),xlab="Years", ylab="PM 2.5 Emissions", main="Motor Vehicle (ON-ROAD) Emissions in Baltimore City from 1999 to 2008")
dev.off()