library(ggplot2)
library(dplyr)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
combo <- merge(NEI,SCC,by="SCC")
balsub <- subset(combo, combo$fips=="24510")
balsub1 <- balsub %>% filter(grepl("vehicle", SCC.Level.Two, ignore.case=TRUE))
agg1 <- aggregate(balsub1$Emissions, by=list(balsub1$year), sum)
names(agg1) <- c("Year", "Emissions")
lasub <- subset(combo, combo$fips=="06037")
lasub1 <- lasub %>% filter(grepl("vehicle", SCC.Level.Two, ignore.case=TRUE))
agg2 <- aggregate(lasub1$Emissions, by=list(lasub1$year), sum)
names(agg2) <- c("Year", "Emissions")
head(agg1)
head(agg2)
ragg <- rbind(agg1,agg2)
vect <- c(rep("Baltimore", times=4), rep("Los Angeles", times=4))
ragg<-cbind(ragg,vect)
names(ragg) <- c("Year", "Emissions", "City") 
g <- ggplot(ragg, aes(factor(Year), Emissions))
g <- g + facet_grid(. ~ City)
g <- g + geom_bar(stat="identity")+ xlab("Year") + ylab("Emissions") + ggtitle("PM 2.5 Emissions Baltimore City vs Los Angeles from 1999 to 2008")
png("plot6(2).png", 840,840)
print(g)
dev.off()