library(ggplot2)
NEI <- readRDS("summarySCC_PM25.rds")
##SCC <- readRDS("Source_Classification_Code.rds")
##head(NEI)
subNEI <- subset(NEI, NEI$fips=="24510")
agg <- aggregate(subNEI$Emissions, by=c(list(subNEI$year), list(subNEI$type)), sum)
##head(agg)
png("plot3(2).png", height=480, width=480)
names(agg) <- c("Year", "Type", "Emissions")
g <- ggplot(agg, aes(x=Year, y=Emissions)) + geom_line(aes(color=Type)) + geom_point(aes(color=Type)) + ylab("PM 2.5 Emissions") + ggtitle("PM 2.5 Emissions by type in Baltimore City, Maryland") 
show(g)
dev.off()